const DAYS = [
  {id:"ma",name:"Maanantai",short:"Ma",type:"sali",badge:"Sali A",title:"Sali A · koko keho",meta:"45–60 min · 2–3 × 10–15 · tauko 60–90 s",intro:"Lämmittely 6–8 min: kuntopyörä tai tasakävely + lonkan avaukset, nilkan pumppaukset, olkapääympyrät.",warn:"Ei syväkyykkyä, hyppyjä eikä raskasta askelkyykkyä. Kipu 0–3/10 ok, terävä kipu tai turvotus seuraavana päivänä ei.",items:[{name:"Jalkaprässi",sets:"2–3",reps:"10–15",place:"Jalkaprässilaite",note:"Jalat hartioiden levyisesti. Liikerata sen verran kuin polvi ja lonkka sallivat."},{name:"Lonkan loitonnus",sets:"2–3",reps:"12–15",place:"Loitonnuslaite, istuen",note:"Tukee lonkkaa sivusuunnassa."},{name:"Lonkan lähennys tai glute-bridge",sets:"2–3",reps:"12–15",place:"Lähennyslaite tai jumppamatto",note:"Bridge selinmakuulla, jos lattia sopii."},{name:"Rintaprässi",sets:"2–3",reps:"10–15",place:"Rintaprässi- tai smith-laite"},{name:"Ylätalja eteen",sets:"2–3",reps:"10–15",place:"Ylätalja, myötäote",note:"Hartiat alas, älä nykäise."},{name:"Keskivartalo",sets:"2–3",reps:"10–15",place:"Vatsalaite tai matto",note:"Vatsarutistus laitteessa tai dead bug / lintukoira, selkä neutraalina."},{name:"Puristus + farmari",sets:"3 + 2",reps:"15–20 / 20–30 m",place:"Pallo + kevyet käsipainot",note:"Pallo molemmille käsille. Farmari vain jos ote ja hartiat kestävät."}]},
  {id:"ti",name:"Tiistai",short:"Ti",type:"walk",badge:"Kävely",title:"Reipas tasainen kävely",meta:"40–55 min · puhetyyli säilyy",intro:"Tavoite on kesto, ei vauhti. Visceraalirasva reagoi kokonaiskulutukseen.",items:[{name:"Kävely tasaisella",sets:"1",reps:"40–55 min",place:"Ulkona tai matolla",note:"Sauvat jos tasapaino tai lonkka kiittää."},{name:"Kengät ja jälkihoito",sets:"–",reps:"–",place:"Pehmeä vakaa lenkkari",note:"Jos polvi turpoaa illalla, lyhennä seuraavaa kävelyä."}]},
  {id:"ke",name:"Keskiviikko",short:"Ke",type:"walk",badge:"Kävely / lepo",title:"Kevyt–reipas kävely tai lepo",meta:"30–40 min · tai lepo jos polvi kipeä",intro:"Tämä on joustopäivä. Polvi päättää.",items:[{name:"Kehittävä kävely",sets:"1",reps:"30–40 min",place:"Tasainen reitti",note:"Rauhallisempi kuin tiistaina."},{name:"Vaihtoehto: lepo",sets:"–",reps:"–",place:"Koti",note:"Valitse lepo, jos oikea polvi tai lonkka on ärtynyt."}]},
  {id:"to",name:"Torstai",short:"To",type:"flex",badge:"Laitepilates",title:"Laitepilates",meta:"Nykyinen tunti · notkeus ja keskivartalo",intro:"Pidä nykyinen tunti. Kerro ohjaajalle polven ja lonkan rajoitteista.",items:[{name:"Laitepilates-tunti",sets:"1",reps:"koko tunti",place:"Pilateslaitteet",note:"Vältä syviä kyykkyjä ja voimakasta lonkan kiertoa, jos sattuu."},{name:"Puristus kotona",sets:"3",reps:"12–20 / käsi",place:"Pehmeä pallo",note:"Voi tehdä myös illalla."}]},
  {id:"pe",name:"Perjantai",short:"Pe",type:"sali",badge:"Sali B",title:"Sali B · jalat, veto, kädet",meta:"45–60 min · 2–3 × 10–15 · tauko 60–90 s",intro:"Sama lämmittely kuin maanantaina.",warn:"Ei vapaapainokyykkyä, maastavetoa lattialta eikä askelkyykkyä eteen.",items:[{name:"Jalkojen ojennus",sets:"2–3",reps:"12–15",place:"Ojennuslaite",note:"Kevyesti. Pysäytä, jos polven etuosa kiristyy terävästi."},{name:"Istuva koukistus",sets:"2–3",reps:"12–15",place:"Takareisilaite"},{name:"Pohkeet",sets:"2–3",reps:"12–15",place:"Prässi tai seisten kaiteesta"},{name:"Alatalja / soutu",sets:"2–3",reps:"10–15",place:"Alatalja tai soutulaite",note:"Kyynärpäät lähellä kylkiä."},{name:"Olkapaaprässi istuen",sets:"2–3",reps:"10–12",place:"Olkapäälaite",note:"Pieni kivuton liikerata."},{name:"Ojentaja ja hauis",sets:"2–3",reps:"10–15",place:"Käsilaite tai kevyet käsipainot",note:"Muotoilee käsivarsia; rasva lähtee kokonaiskulutuksella."},{name:"Puristus + sormien ojennus",sets:"3 + 2",reps:"15–20 / 15",place:"Pallo + kuminauha"}]},
  {id:"la",name:"Lauantai",short:"La",type:"walk",badge:"Kävely",title:"Pidempi kävely",meta:"40–55 min · loivat mäet vain jos polvi ok",intro:"Peruskävely. Mäkivedot vain rauhalliseen polveen.",items:[{name:"Kävely",sets:"1",reps:"40–55 min",place:"Ulkona",note:"Sauvat sallittu."},{name:"Valinnainen: loivat vedot",sets:"6",reps:"2 min reipas + 2 min kevyt",place:"Loiva nousu, ei portaita",note:"Jätä pois, jos oikea polvi kipeytyy."}]},
  {id:"su",name:"Sunnuntai",short:"Su",type:"flex",badge:"Yin",title:"Yin-jooga",meta:"Nykyinen tunti · palautuminen",intro:"Pidä yin. Älä pakota polvea tai lonkkaa ääriasentoihin.",items:[{name:"Yin-tunti",sets:"1",reps:"koko tunti",place:"Joogasali / koti"},{name:"Valinnainen helppo kävely",sets:"1",reps:"20–30 min",place:"Tasainen",note:"Vain jos olo on kevyt."}]}
];
const STORAGE="treeni-v1";
const todayId=["su","ma","ti","ke","to","pe","la"][new Date().getDay()];
function load(){try{return JSON.parse(localStorage.getItem(STORAGE)||"{}");}catch(e){return{};}}
function save(data){localStorage.setItem(STORAGE,JSON.stringify(data));}
function weekKey(){const d=new Date();const onejan=new Date(d.getFullYear(),0,1);const week=Math.ceil((((d-onejan)/86400000)+onejan.getDay()+1)/7);return d.getFullYear()+"-w"+week;}
function keyFor(dayId,idx){return weekKey()+":"+dayId+":"+idx;}
const state=load();
function doneCount(day){return day.items.filter(function(_,i){return state[keyFor(day.id,i)];}).length;}
function weekDone(){return DAYS.filter(function(d){return doneCount(d)===d.items.length;}).length;}
function renderFooter(){document.getElementById("weekProg").textContent="Viikko "+weekDone()+"/7 päivää merkitty valmiiksi";}
function renderNav(){const nav=document.getElementById("nav");nav.innerHTML=DAYS.map(function(d){return '<button data-id="'+d.id+'" class="'+(d.id===todayId?"active":"")+'">'+d.short+"</button>";}).join("");nav.querySelectorAll("button").forEach(function(b){b.onclick=function(){show(b.dataset.id);};});}
function show(id){const day=DAYS.find(function(d){return d.id===id;});document.querySelectorAll("nav button").forEach(function(b){b.classList.toggle("active",b.dataset.id===id);});const pct=Math.round(100*doneCount(day)/day.items.length);const typeClass=day.type==="sali"?"sali":day.type==="walk"?"walk":"flex";document.getElementById("app").innerHTML='<div class="card"><span class="badge b-'+typeClass+'">'+day.badge+"</span><h2>"+day.title+"</h2><div class=\"meta\">"+day.name+" · "+day.meta+"</div><p>"+day.intro+"</p>"+(day.warn?'<p class="warn">'+day.warn+"</p>":"")+'<div class="progress"><span style="width:'+pct+'%"></span></div><div class="meta">'+doneCount(day)+"/"+day.items.length+" merkitty</div></div>"+day.items.map(function(ex,i){return '<div class="card"><h3>'+(i+1)+". "+ex.name+"</h3><div class=\"nums\"><span class=\"chip\">Paikka: "+ex.place+"</span><span class=\"chip\">Sarjat "+ex.sets+"</span><span class=\"chip\">Toistot "+ex.reps+"</span></div>"+(ex.note?'<div class="note">'+ex.note+"</div>":"")+'<label class="check"><input type="checkbox" data-k="'+keyFor(day.id,i)+'"'+(state[keyFor(day.id,i)]?" checked":"")+"/> Tehty</label></div>";}).join("");document.querySelectorAll("input[type=checkbox]").forEach(function(cb){cb.onchange=function(){state[cb.dataset.k]=cb.checked;save(state);show(id);renderFooter();};});}
document.getElementById("todayBtn").onclick=function(){show(todayId);};
renderNav();show(todayId);renderFooter();
